$\newcommand{R}[0]{\mathbb{R}}$ 
# Resolução da Primeira lista de exercícios - MAC0460/MAC5832

##### Professores: Igor dos Santos Montagner e Roberto Hirata Jr.

###### Data entrega: 23h55m do dia 17/03/2016


##### Aluno: Thales A. B Paiva - 7156390 - <thalespaiva@gmail.com>
**8/03/2016**

*Uma versão atualizada desta resolução pode ser encontrada no meu GitHub, em: https://github.com/thalespaiva/machlearn*.

Exercício 1: Utilizando o *numpy*, crie os seguintes vetores e matrizes ($v \in \R^5, A \in \R^{5\times 5}, B \in \R^{5\times 4}$)

$$
v=\begin{bmatrix}
62\\
13\\
84\\
23\\
96\end{bmatrix},
A=\begin{bmatrix}
23 & 43 & 34 & 86 & 324 \\
36& 177 & 435 & 865 & 346 \\
43 & 546 & 345 & 32 & 86 \\
45 & 23 & 875  & 452 & 435 \\
6543 & 32432& 4532 & 489 & 34\end{bmatrix},
B=\begin{bmatrix}
65 & 23& 889 & 34 \\
12 & 128 & 23 & 85 \\
44 & 48 & 67 & 895 \\
97 & 37 & 65 & 867 \\
22 & 55 & 44 & 33
\end{bmatrix}
$$



In [1]:
import numpy as np

In [2]:
v = np.array([62, 13, 84, 23, 96])

In [3]:
A = np.matrix([ 
        [23  , 43   , 34  , 86 , 324],
        [3   , 177  , 435 , 865, 346],
        [43  , 546  , 345 , 32 , 86 ],
        [45  , 23   , 875 , 452, 435],
        [6543, 32432, 4532, 489, 34 ],
    ])

In [4]:
B = np.matrix([
        [65 , 2  , 889, 34 ],
        [12 , 128, 23 , 85 ],
        [44 , 48 , 67 , 895],
        [97 , 37 , 65 , 867],
        [22 , 55 , 44 , 33 ],
    ])

Imprima abaixo os elementos $v_2, A_{1, 3}$ e $B_{4, 4}$.

*Assumindo que v_i se refere à i-ésima entrada do vetor v*

In [5]:
print('v[1] = ', v[1])
print('A[0][2] = ', A[0,2])
print('B[3][3] = ', B[3,3])


v[1] =  13
A[0][2] =  34
B[3][3] =  867


Usando a notação de *slices* do Numpy, imprima os elementos 2 a 4 de $v$, a segunda coluna e a terceira linha de $A$ e a submatriz $B$ que vai do elemento $(2,1)$ até o elemento $(3, 4)$.

*Assumindo que imprimir os elementos de 2 a 4 significa imprimir o segundo, o terceiro e o quarto, inclusive, do vetor.*

In [6]:
print(v[1:4])

[13 84 23]


In [7]:
print(A[:,1])

[[   43]
 [  177]
 [  546]
 [   23]
 [32432]]


In [8]:
print(A[3,:])

[[ 45  23 875 452 435]]


In [9]:
print(B[1:3,0:4])

[[ 12 128  23  85]
 [ 44  48  67 895]]


Calcule o produto interno de $v$ pelo vetor 
$u = \begin{bmatrix}
4 \\
23 \\
44\\
65\\
12
\end{bmatrix}$ e as multiplicações $AB, v^TA$ e $B^Tv$.

In [10]:
u = np.array([4, 23, 44, 65, 12])

In [11]:
print(v.dot(u))

6890


In [12]:
print(A.dot(B))

[[  18977   28184   43560  120121]
 [ 112976   94577  107332 1165845]
 [  29523   92448   79764  387229]
 [  95115   85683  147679 1192849]
 [1062068 4401881 6899588 7460407]]


In [13]:
print(v.dot(A))

[[ 634240 3164832  491940   76605   45079]]


In [14]:
print(B.T.dot(np.matrix(v).T))

[[ 12225]
 [ 11951]
 [ 66764]
 [101502]]


Calcule o determinante, os autovalores e os autovetores de $A$. Verifique que os autovetores resultantes são realmente válidos para todos os pares de autovalores/autovetores de $A$.

In [15]:
import numpy.linalg as la

In [16]:
print('det(A) = ', la.det(A))

det(A) =  -4.72416476933e+14


In [17]:
eigen_vals, eigen_vecs_transp = la.eig(A)

In [18]:
for i, val, vec in zip(range(len(eigen_vals)), eigen_vals, eigen_vecs_transp.T):
    diff = A.dot(vec.T) - (val*vec).T
    print("|A*eigen_vec[%d] - eigen_val[%d]*eigen_vec[%d]| = %.6f " % (i, i, i, np.linalg.norm(diff)))

|A*eigen_vec[0] - eigen_val[0]*eigen_vec[0]| = 0.000000 
|A*eigen_vec[1] - eigen_val[1]*eigen_vec[1]| = 0.000000 
|A*eigen_vec[2] - eigen_val[2]*eigen_vec[2]| = 0.000000 
|A*eigen_vec[3] - eigen_val[3]*eigen_vec[3]| = 0.000000 
|A*eigen_vec[4] - eigen_val[4]*eigen_vec[4]| = 0.000000 


Verifique se $A$ é invertível. Se sim, inverta-a.

*Já vimos que $det(A) \neq 0$. Então:*

In [19]:
Ainv = la.inv(A)

In [20]:
print("Inversa de A arredondada em .4 :\n", Ainv.round(decimals=4))

Inversa de A arredondada em .4 :
 [[-0.0009 -0.0019 -0.0115  0.0045  0.0002]
 [ 0.0004  0.0004  0.0022 -0.0011 -0.    ]
 [-0.0013 -0.0005  0.0007  0.0012 -0.    ]
 [-0.0008  0.0014 -0.0011 -0.0003  0.    ]
 [ 0.0035 -0.0002  0.0007 -0.0002 -0.    ]]


Qual é a relação entre o determinante de $A$ e seus autovalores? Verifique que esta relação é valida para os valores calculados acima. 

*O determinante de uma matriz $A$ é o produto de seus autovalores.*

In [21]:
def product(elements):
    prod = 1
    for el in elements:
        prod *= el
    return prod

In [22]:
la.norm(product(eigen_vals) - la.det(A))

0.5625

*O fato de a diferença absoluta não ter dado 0 é facilmente explicado pelos erros de arredondamento. Considere a diferença relativa.*

In [23]:
detA = la.det(A)

In [24]:
eigen_prod = product(eigen_vals)

In [25]:
print("(eigen_prod - detA)/detA ~= %.6f" % la.norm((eigen_prod - detA)/detA))

(eigen_prod - detA)/detA ~= 0.000000


Calcule a matrix de Gram $B$ e calcule a matriz quadrada $P$ e a matriz diagonal $S$ de sua diagonalização.

*$Gram(B) = B^TB$, então: *

In [26]:
GramB = B.T.dot(B)

In [27]:
GramB

matrix([[  16198,    8577,   68282,  127435],
        [   8577,   23086,   12763,   87802],
        [  68282,   12763,  801500,  149953],
        [ 127435,   87802,  149953, 1562184]])

*Queremos matrizes $P$ e $S$ tais que $Gram(B) = PSP^{-1}$. Uma solução é tomar S a matriz com os autovalores na diagonal principal e P a matriz com os autovetores associados nas colunas.*

In [28]:
evalues, Ptransp = la.eig(GramB)

In [29]:
def diagonalize(M):
    eigen_values, eigen_vectors_transp = la.eig(M)
    S = np.diag(eigen_values)
    P = eigen_vectors_transp
    return (P, S, la.inv(P))

In [30]:
P, S, Pinv = diagonalize(GramB)

In [31]:
print(S.round(4))

[[ 1607690.0776        0.            0.            0.    ]
 [       0.       775425.4403        0.            0.    ]
 [       0.            0.         1719.3722        0.    ]
 [       0.            0.            0.        18133.1099]]


Compare $Gram(B)$ com $PSP^{-1}$:

In [32]:
diff = P.dot(S).dot(Pinv) - GramB

In [33]:
print(diff.round(6))

[[ 0.  0.  0.  0.]
 [-0.  0. -0. -0.]
 [ 0. -0.  0. -0.]
 [-0. -0.  0.  0.]]


Verifique se $A$ é positiva (semi) definida.

*Uma matriz é definida positiva se e somente se admite uma decomposição de Cholesky.*

In [34]:
try:
    la.cholesky(A)
    print('A é semidefinida positiva.')
except la.LinAlgError:
    print('A não é semidefinida positiva.')

A não é semidefinida positiva.


Calcule a decomposição SVD de $B$. Verifique que o vetor $V$ devolvido contém os autovetores da matrix de Gram calculada acima.

In [35]:
U, s, V = la.svd(B, full_matrices=True)

*Compare as colunas de $V^T$ e P. Note que, a menos da ordem em que aparecem, e de direção, são os mesmos vetores:*

In [36]:
V.T

matrix([[ 0.08662811, -0.05527972,  0.06166129,  0.99279283],
        [ 0.05609836,  0.00551247,  0.99619555, -0.06646067],
        [ 0.18983336, -0.97923331, -0.00997274, -0.0704696 ],
        [ 0.9763769 ,  0.19497664, -0.06076893, -0.07056491]])

In [37]:
P

matrix([[-0.08662811,  0.05527972, -0.99279283, -0.06166129],
        [-0.05609836, -0.00551247,  0.06646067, -0.99619555],
        [-0.18983336,  0.97923331,  0.0704696 ,  0.00997274],
        [-0.9763769 , -0.19497664,  0.07056491,  0.06076893]])